[package]
name = "fw-anwesenheit"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.40", features = ["serde"] }
gpio = "0.4.1"
regex = "1.11.1"
<<<<<<< HEAD
rppal = "0.22.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
=======
rocket = "0.5.1"
tokio = { version = "1.44.2", features = ["full"] }
>>>>>>> eb39b09632efb1568079352e3d639edc79df65fd
