[package]
name = "fw-anwesenheit"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.40", features = ["serde"] }
regex = "1.11.1"
rocket = "0.5.1"
tokio = { version = "1.44.2", features = ["full"] }
